export const TIERS = [
  {
    label: "Tier 1",
    description: "DG Rank 1–10",
    golfers: [
      "Scottie Scheffler",
      "Rory McIlroy",
      "Collin Morikawa",
      "Xander Schauffele",
      "Ludvig Åberg",
      "Tommy Fleetwood",
      "Jon Rahm",
      "Bryson DeChambeau",
      "Viktor Hovland",
      "Patrick Cantlay",
    ],
  },
  {
    label: "Tier 2",
    description: "DG Rank 11–20",
    golfers: [
      "Shane Lowry",
      "Russell Henley",
      "Hideki Matsuyama",
      "Cameron Smith",
      "Joaquin Niemann",
      "Min Woo Lee",
      "Tony Finau",
      "Keegan Bradley",
      "Jordan Spieth",
      "Justin Thomas",
    ],
  },
  {
    label: "Tier 3",
    description: "DG Rank 21–30",
    golfers: [
      "Adam Scott",
      "Corey Conners",
      "Sepp Straka",
      "Brian Harman",
      "Tyrrell Hatton",
      "Sungjae Im",
      "Matt Fitzpatrick",
      "Robert MacIntyre",
      "Akshay Bhatia",
      "Denny McCarthy",
    ],
  },
  {
    label: "Tier 4",
    description: "DG Rank 31–45",
    golfers: [
      "Sergio Garcia",
      "Stephan Jaeger",
      "Jason Day",
      "Wyndham Clark",
      "Harris English",
      "Cameron Young",
      "Tom Kim",
      "J.J. Spaun",
      "Nicolai Højgaard",
      "Aaron Rai",
      "Rasmus Højgaard",
      "Brooks Koepka",
      "Patrick Reed",
      "Talor Gooch",
      "Abraham Ancer",
    ],
  },
  {
    label: "Tier 5",
    description: "DG Rank 46–65",
    golfers: [
      "Sahith Theegala",
      "Si Woo Kim",
      "Billy Horschel",
      "Dustin Johnson",
      "Thomas Detry",
      "Nick Taylor",
      "Thriston Lawrence",
      "Ryo Hisatsune",
      "Matthieu Pavon",
      "Christiaan Bezuidenhout",
      "Davis Riley",
      "Adam Hadwin",
      "Max Greyserman",
      "Byeong Hun An",
      "Austin Eckroat",
    ],
  },
  {
    label: "Tier 6",
    description: "DG Rank 66+ / Field",
    golfers: [
      "Phil Mickelson",
      "Tiger Woods",
      "Fred Couples",
      "Bernhard Langer",
      "Jose Maria Olazabal",
      "Mike Weir",
      "Vijay Singh",
      "Larry Mize",
      "Sandy Lyle",
      "Bubba Watson",
      "Justin Rose",
      "Charl Schwartzel",
      "Zach Johnson",
      "Matteo Manassero",
      "Santiago de la Fuente",
      "Neal Shipley",
      "Jacob Bridgeman",
      "Austin Eckroat",
    ],
  },
]

export const MASTERS_GOLFERS = TIERS.flatMap(t => t.golfers)
